INSERT INTO DEPARTMENT VALUES ('-1', '', '总公司');

INSERT INTO SECURITY VALUES (UPPER(REPLACE(UUID(),'-','')), '1001', '发起会议');
INSERT INTO SECURITY VALUES (UPPER(REPLACE(UUID(),'-','')), '1002', '修改会议');
INSERT INTO SECURITY VALUES (UPPER(REPLACE(UUID(),'-','')), '1003', '删除会议');
INSERT INTO SECURITY VALUES (UPPER(REPLACE(UUID(),'-','')), '1004', '结束会议');
INSERT INTO SECURITY VALUES (UPPER(REPLACE(UUID(),'-','')), '1005', '材料下载');
INSERT INTO SECURITY VALUES (UPPER(REPLACE(UUID(),'-','')), '1006', '会议室增加');
INSERT INTO SECURITY VALUES (UPPER(REPLACE(UUID(),'-','')), '1007', '会议室修改');
INSERT INTO SECURITY VALUES (UPPER(REPLACE(UUID(),'-','')), '1008', '会议室删除');

INSERT INTO SECURITY VALUES (UPPER(REPLACE(UUID(),'-','')), '2001', '职务增加');
INSERT INTO SECURITY VALUES (UPPER(REPLACE(UUID(),'-','')), '2002', '职务修改');
INSERT INTO SECURITY VALUES (UPPER(REPLACE(UUID(),'-','')), '2003', '职务删除');
INSERT INTO SECURITY VALUES (UPPER(REPLACE(UUID(),'-','')), '2004', '部门增加');
INSERT INTO SECURITY VALUES (UPPER(REPLACE(UUID(),'-','')), '2005', '部门修改');
INSERT INTO SECURITY VALUES (UPPER(REPLACE(UUID(),'-','')), '2006', '部门删除');
INSERT INTO SECURITY VALUES (UPPER(REPLACE(UUID(),'-','')), '2007', '用户增加');
INSERT INTO SECURITY VALUES (UPPER(REPLACE(UUID(),'-','')), '2008', '用户修改');
INSERT INTO SECURITY VALUES (UPPER(REPLACE(UUID(),'-','')), '2009', '用户删除');
INSERT INTO SECURITY VALUES (UPPER(REPLACE(UUID(),'-','')), '2010', '角色增加');
INSERT INTO SECURITY VALUES (UPPER(REPLACE(UUID(),'-','')), '2011', '角色修改');
INSERT INTO SECURITY VALUES (UPPER(REPLACE(UUID(),'-','')), '2012', '角色删除');
INSERT INTO SECURITY VALUES (UPPER(REPLACE(UUID(),'-','')), '2013', '角色保存');
INSERT INTO SECURITY VALUES (UPPER(REPLACE(UUID(),'-','')), '2014', '角色重置');
INSERT INTO SECURITY VALUES (UPPER(REPLACE(UUID(),'-','')), '2015', '角色全选');

INSERT INTO SECURITY VALUES (UPPER(REPLACE(UUID(),'-','')), '3001', '短信中心保存');

INSERT INTO SEX VALUES ('0', '01', '男');
INSERT INTO SEX VALUES ('1', '02', '女');

INSERT INTO MEETING_MEMBER_ROLE VALUES ('0', '01', '会议发起人');
INSERT INTO MEETING_MEMBER_ROLE VALUES ('1', '02', '会议主持人');
INSERT INTO MEETING_MEMBER_ROLE VALUES ('2', '03', '其它参会人员');

INSERT INTO ATTACHMENT_CATEGORY VALUES ('0', '01', '普通附件');
INSERT INTO ATTACHMENT_CATEGORY VALUES ('1', '02', '会议记录');

INSERT INTO MEETING_STATE VALUES ('0', '01', '已发起');
INSERT INTO MEETING_STATE VALUES ('1', '02', '已结束');

INSERT INTO MESSAGE_SEND_STATE VALUES ('0', '01', '未发送');
INSERT INTO MESSAGE_SEND_STATE VALUES ('1', '02', '发送失败');
INSERT INTO MESSAGE_SEND_STATE VALUES ('2', '03', '发送成功');